### ISSUE TITLE
Suggestion: SoundSetter Alias' for existing text commands

### ISSUE THREAD

**Issue by Mad-Guns22** [karashiiro/SoundSetter#1]
Is is possible to have as default or set as an option for the existing ingame chat volume commands such as /mastervolume, /bgm, /voice to also be toggle or set the value while in cut scenes or instances where chat is accessible but the command wont trigger?

**Comment by karashiiro** [comment]
Sorry for the late response, my webhook channel is getting a bit cluttered ^^

I'll look into it, overriding native commands is a bit more complicated than just adding new ones, but I'm pretty sure it can be done. At worst, I'll add new commands that function the same way.

**Comment by karashiiro** [comment]
Forgot about this, but https://github.com/karashiiro/SoundSetter/commit/96c001c9d2bd0d627986a47b872f3c2330161af9 goes part of the way towards resolving this.

**Comment by karashiiro** [comment]
With the addition of the mute/unmute subcommands, the plugin commands should now be sufficient replacements for the native commands.
