### ISSUE TITLE
Mute toggle for macros

### ISSUE THREAD

**Issue by GunB** [karashiiro/SoundSetter#13]
So, It would be really amazing if there was a way to instead of using 2 buttons for macros to turn on/off the bgm, we could just /ssbgm mute toggle

FFXIV music gets old and I usually just turn it on at raids because usually, the music aligns with mechanics so it's good to have it.

I would appreciate this a lot, for every macro command you have, so I don't need 2 buttons to do a toggle.

**Comment by karashiiro** [comment]
Isn't this already a thing? If you just use the commands without any parameters it should do that.

**Comment by karashiiro** [comment]
Yeah, it's in the error command: https://github.com/karashiiro/SoundSetter/blob/master/SoundSetter/ErrorMessages.cs#L12

**Comment by GunB** [comment]
OHHHHHHHHHH Ok! Sorry it wasn't super clear for me. Thank you for the heads up
