### ISSUE TITLE
Update for 6.2

### ISSUE THREAD

**Issue by ichi-obi** [karashiiro/SoundSetter#20]

**Comment by karashiiro** [comment]
Yeah, the hook I need might've changed significantly, I spent an hour messing with it yesterday before setting it aside. I haven't forgotten about this, it's just more annoying than usual this patch.

**Comment by karashiiro** [comment]
Will be updated once [this](https://github.com/goatcorp/DalamudPluginsD17/pull/270) is merged, closing.
