### ISSUE TITLE
Not sure how to adress that tbh..

### ISSUE THREAD

**Issue by NevendyND** [karashiiro/SoundSetter#21]
![hdrh](https://user-images.githubusercontent.com/28860034/188499052-4bb36df6-0ef4-416b-b4d6-104008e16265.PNG)

**Comment by karashiiro** [comment]
Are you using Wine? I've noticed Wine-based installs have imgui rendering bugs in general. If so, this should probably be reported to the platform maintainer's server (goat place or XOM).

**Comment by NevendyND** [comment]
Not that i know of it that i use "Wine-based installs".
I only know that it was not there yesterday, i will look into it i guess

**Comment by karashiiro** [comment]
Sorry, I should've just said Linux/Mac instead of Wine-based. If this is Windows, you should get support from the XIVLauncher maintainers, since this looks like a rendering bug, which is beyond the scope of this plugin.

**Comment by NevendyND** [comment]
okay, after reinstalling all, it got fixed
