### ISSUE TITLE
Add feature to allow relative volume changes

### ISSUE THREAD

**Issue by SyntaxVoid** [karashiiro/SoundSetter#24]
It might be nice to have some kind of syntax that allows you to do something like "increase volume by 5" or "decrease volume by 10"

Maybe something like

`/ssmv +5`

or

`/ssmv -10`

**Comment by SyntaxVoid** [comment]
Sorry, I just tested this and realized this already exists. I had tried incorrectly before

**Comment by karashiiro** [comment]
Is this not already implemented? The README seems to document exactly what you're describing.
