### ISSUE TITLE
Update pls :D 

### ISSUE THREAD

**Issue by Gitterzwerg** [karashiiro/SoundSetter#25]
Needs update for current patch pls :D

**Comment by karashiiro** [comment]
![image](https://github.com/karashiiro/SoundSetter/assets/49822414/d009021a-ce70-45ce-9ce7-0f5eeecabbda)

https://na.finalfantasyxiv.com/lodestone/topics/detail/d7db61f938f9cea65e4c5cd261918edb036b3004

Most of SoundSetter's functionality has officially been added to the game, so I'm actually planning to archive this 👀

**Comment by skonrad** [comment]
Still prefer to use a shortcut and the nice UI it had (better than the default in all aspects).

Not sure I'll be able to remember all the text commands xD

**Comment by hmm-norah** [comment]
The official command doesn't support increment/decrement commands for some mind-boggling reason. I would really miss this plugin going away if it's archived.
![ffxiv_dx11_GvyYpB4G4F](https://github.com/karashiiro/SoundSetter/assets/696702/cabecd45-6837-4382
![ffxiv_dx11_S1bijhHEt7](https://github.com/karashiiro/SoundSetter/assets/696702/5269eb94-cd5e-49bc-9844-c2663f053057)
-b6d1-9db5f151c1e8)
![ffxiv_dx11_522OgHy8C5](https://github.com/karashiiro/SoundSetter/assets/696702/c104cde4-0a29-43c0-9a1f-5557a3d62067)

**Comment by ltsLumina** [comment]
What changes would be required to make this work with Dawntrail? I would personally update it myself if I were informed of what needs to be changed for it to function with the new patch.
I really appreciate the UI this plugin gives and would be sad to see it go.

**Comment by karashiiro** [comment]
Either the plugin needs to be refactored to use Dalamud's newer [IGameConfig](https://github.com/goatcorp/Dalamud/blob/master/Dalamud/Plugin/Services/IGameConfig.cs) service, or the new configuration option offsets need to be reverse-engineered or determined through trial and error - there's a tool for updating them once you know what they are, but figuring out the offsets is tedious.

**Comment by karashiiro** [comment]
I can find some time to update it at some point if nobody else manages to, since people seem to still want it - just not sure when exactly that will be since I wasn't planning for it (and Universalis is down again which is a bigger issue).

**Comment by ltsLumina** [comment]
Take your time with Universalis, it is significantly more valuable to the community than this plugin. But if you do find the time to work on this, the community and I will be sincerely grateful.

**Comment by chiyumeh** [comment]
As Lumina said, take your time with Universalis but I'd really appreciate an update for SoundSetter, it may be simple but it's by far my most used and favorite QoL plugin and the now native functions just don't cut it! <3

**Comment by karashiiro** [comment]
Update pending approval: https://github.com/goatcorp/DalamudPluginsD17/pull/3945

**Comment by ltsLumina** [comment]
> Update pending approval: [goatcorp/DalamudPluginsD17#3945](https://github.com/goatcorp/DalamudPluginsD17/pull/3945)

Thank you!
