### ISSUE TITLE
Changing sound manually is required to use plugin command

### ISSUE THREAD

**Issue by afourmeaux** [karashiiro/SoundSetter#26]
Hello,

When using /ssbgm or /ssas there is this messaga appearing "Please manually change a volume setting once in order to initialize the plugin" after doing that the commands works. But when relogging the message reappear. It kinda defeat the purpose of the plugin if i have to do it manually😅

I think this problem appeared after the dawntrail update. So is it a bug ? A feature ? Am i the only one having this issue ?

**Comment by karashiiro** [comment]
It's always been like this, I just haven't had time to rewrite it to improve it yet. It requires changing volume settings manually once per login so it can find where the configuration is in-memory, which it then uses for commands etc.

**Comment by afourmeaux** [comment]
ok, so it's strange because i definitely didn't need to set it manually before. Anyway, thank for the answer.

**Comment by Theletha** [comment]
> ok, so it's strange because i definitely didn't need to set it manually before. I only used /ssbgm and /ssas without any value to toggle on or off those sounds. Anyway, thank for the answer.

Same. I noticed this too now in dawntrail release. Never had to do it manually before. thought it was a dawntrail bug.

![image](https://github.com/user-attachments/assets/80c1425a-8401-4e0f-8725-1247a85bd178)

**Comment by Haddude** [comment]
> ok, so it's strange because i definitely didn't need to set it manually before. I only used /ssbgm and /ssas without any value to toggle on or off those sounds. Anyway, thank for the answer.

Same for me, prior to Dawntrail I did not have to change a volume setting upon each log-in.

**Comment by karashiiro** [comment]
I usually toggle the plugin on and off frequently for development reasons which requires a manual toggle to work, so I might just be mixing up the normal behavior with that.

I think the way it worked before was that logging in did some config loading that actually worked like a manual toggle, which is why it wasn't an issue. For one reason or another (maybe some optimization SE did), that isn't happening now.

**Comment by afourmeaux** [comment]
In the end i found that there are [ingame commands to handle sounds](https://ffxiv.consolegameswiki.com/wiki/Text_commands) (search for the keyword "volume"). In my case i replaced the addon commands by /bgm & /ambientsounds to do what i did with the addon and they work like a charm.

**Comment by karashiiro** [comment]
This will be fixed in v1.10.0 (also updates the plugin for 7.1 in general): https://github.com/goatcorp/DalamudPluginsD17/pull/5060

**Comment by Theletha** [comment]
glad there was a fix for it !
